feat(modules): reload modules in require
jank-lang/jank pull request #155
Opened 2024-12-28 18:40 UTC by Samy-33

2025-01-02 04:54 UTC, Samy-33 commented
@jeaye

2025-01-02 22:31 UTC, jeaye requested changes

2025-01-02 22:31 UTC, jeaye commented on compiler+runtime/include/cpp/jank/jit/processor.hpp
> +      return err("Failed to find symbol");
Please use `Failed to find symbol '{}'` and format in the symbol. We can all be helping with error reporting by generating better errors. :)

2025-01-02 22:31 UTC, jeaye commented on compiler+runtime/include/cpp/jank/jit/processor.hpp
> +#include <boost/filesystem/path.hpp>
Why is this here? I don't see it being used in this header.

2025-01-02 22:31 UTC, jeaye commented on compiler+runtime/include/cpp/jank/runtime/core/munge.hpp
> +#include <regex>
Because of this, everyone who includes `munge.hpp` now needs to include all of the C++ regex headers. That's another ~5k lines of C++ source. Since this header is part of `runtime/core.hpp`, it's included very often and now every single one of those (dozens of) translation units needs to pay the cost of parsing the C++ regex library, even though `munge_extra` is used only in two of them.

Instead, consider:

1. Forward declaring the regex bits you need (this is very tough, in this case, since `std::regex` is an alias of a template)
2. Moving `std::regex` into the `.cpp` file by instead taking a string for the search and turning it into a regex
3. Moving `munge_extra` into a new `munge_ext.hpp`, like I did with `seq_ext.hpp`

In this case, I would likely go with option 2 if I were writing it. However, I write all of this up to get you thinking about compile times when you're writing code. In jank, compile times aren't just compile time, either, since we will need to include C++ headers at runtime for seamless C++ interop. We want those headers to be as light as possible. But even without that, we want our project to compile as fast as possible. With where we are, I want jank to be *faster* to compile in 6 months, not slower. We will get there by applying more mindful methodologies to what we put in headers.

2025-01-02 22:31 UTC, jeaye commented on compiler+runtime/include/cpp/jank/runtime/ns.hpp
> +    std::atomic_uint64_t symbol_counter{};
Any reason you switched from `atomic_size_t` to `atomic_uint64_t`?

2025-01-02 22:31 UTC, jeaye commented on compiler+runtime/src/cpp/jank/c_api.cpp
> +  void jank_ns_set_symbol_counter(char const * const ns, uint64_t count)
Please make `count` const.

2025-01-02 22:31 UTC, jeaye commented on compiler+runtime/include/cpp/jank/c_api.h
> +  void jank_ns_set_symbol_counter(char const * const ns, uint64_t count);
Why did you change this from a `size_t` to a `uint64_t`?

2025-01-02 22:31 UTC, jeaye commented on compiler+runtime/src/cpp/jank/codegen/llvm_processor.cpp
> +
Please write a comment here for the future us which explains why this whole dance is needed. It's not at all obvious.

2025-01-02 22:31 UTC, jeaye commented on compiler+runtime/src/cpp/jank/jit/processor.cpp
> +    auto const error = ee.getMainJITDylib().remove(to_remove);
Please always use direct initialization.

2025-01-02 22:31 UTC, jeaye commented on compiler+runtime/src/cpp/jank/jit/processor.cpp
> +      return err(fmt::format("Failed to remove the symbol: {}", name));
Please use the format: "Failed to remove the symbol '{}'"

2025-01-02 22:31 UTC, jeaye commented on compiler+runtime/src/cpp/jank/runtime/core/munge.cpp
> +#include <regex>
I left a comment about you including this header in `munge.hpp`, but I also want to now point out that you're *also* including it in `munge.cpp`, (and other files in this PR) which makes the problem even worse. :joy:

2025-01-02 22:31 UTC, jeaye commented on compiler+runtime/src/cpp/jank/runtime/core/seq.cpp
> +                     || std::same_as<S, obj::persistent_sorted_set>)
We want `behavior::set_like` here.

2025-01-02 22:31 UTC, jeaye commented on compiler+runtime/src/cpp/jank/runtime/module/loader.cpp
> +     * */
So this means that it'll be impossible, in jank, to:

1. Load a module from an object file
2. Change the source behind that module
3. Try to require the module again, to reload it
4. Get the updated source

What does Clojure do here?

2025-01-03 03:39 UTC, Samy-33 commented on compiler+runtime/include/cpp/jank/jit/processor.hpp
> +#include <boost/filesystem/path.hpp>
Clangd shows error, without this `include`

Being used at the bottom of this file.

2025-01-03 05:11 UTC, Samy-33 commented on compiler+runtime/src/cpp/jank/runtime/module/loader.cpp
> +     * */
If the source is more recent than the object file, we will always load from source.

Clojure doesn't load from `class` files, while `reloading` in the repl.

2025-01-03 06:38 UTC, jeaye commented on compiler+runtime/include/cpp/jank/jit/processor.hpp
> +#include <boost/filesystem/path.hpp>
Ok, not new code. Please make sure stdlib headers are first. Then dependency headers. Then jank headers.

2025-01-14 17:09 UTC, Samy-33 commented on compiler+runtime/include/cpp/jank/runtime/ns.hpp
> +    std::atomic_uint64_t symbol_counter{};
I couldn't figure out how to generate IR for `size_t` while calling the `jank_set_ns_symbol_counter`.

For `atomic_uint64_t` I could use the `ctx->builder->getInt64Ty()`. But couldn't find an equivalent for size_t.

Would appreciate if you could point me to the correct place.

2025-01-14 17:10 UTC, Samy-33 commented on compiler+runtime/src/cpp/jank/runtime/core/munge.cpp
> +#include <regex>
How does including it into cpp much worse than just including it in hpp?

I understand why including `regex` in hpp would be a problem and also including it in a `cpp` would be worse. But your comment feels like, it's extremely bad on top of just `hpp`?

Could you help me understand ?

2025-01-14 17:11 UTC, Samy-33 commented on compiler+runtime/src/cpp/jank/runtime/module/loader.cpp
> +     * */
Let me know, if this makes sense?

2025-01-15 02:02 UTC, jeaye commented on compiler+runtime/include/cpp/jank/runtime/ns.hpp
> +    std::atomic_uint64_t symbol_counter{};
Ah, I see. The IR is what led to this. Ok, we can keep it as is in order to be a better 1:1 fit with the IR.

2025-01-16 19:32 UTC, jeaye commented on compiler+runtime/include/cpp/jank/jit/processor.hpp
> +#include <fmt/format.h>
`fmt` is not permitted within normal headers. Please use our `util/string_builder` instead. `fmt` is too heavy and I have stripped it from every normal header and replaced it with a custom string builder which is much lighter to compile.

The commit for that is here: https://github.com/jank-lang/jank/commit/23aba5503bd5c3455511bf5e4ccc9e1b50e623ea

General usage:

```cpp
return err(util::string_builder{}("Failed to find the symbol: '")(name)("'")).release();
```

2025-01-16 20:05 UTC, Samy-33 commented on compiler+runtime/include/cpp/jank/jit/processor.hpp
> +#include <fmt/format.h>
Done

2025-01-16 20:25 UTC, merged

2025-01-17 07:35 UTC, Samy-33 commented
Handles #139 : `Load binaries only if the source isn't newer`